networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: 'mongo:4.4.6'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cl
      - MONGO_INITDB_ROOT_PASSWORD=cl123
      - MONGO_INITDB_DATABASE=cl_db
    ports:
      - 27017:27017
    networks:
      - app-tier
  # myapp:
  #   image: 'client:latest'
  #   networks:
  #     - app-tier