version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db-client:
    container_name: db-client
    image: chengkuan/mongodb-5.0.2
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USERNAME=cl
      - MONGODB_ROOT_PASSWORD=cl123
      - MONGODB_DATABASE=cl_db
    ports:
      - "27018:27017"
    volumes:
      - ./db:/data/db
    networks:
      - app-tier

  py-client:
    container_name: py-client
    image: py-client:latest
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-arm32
    entrypoint: python -u /client.py ${SERVER_HOSTNAME} db-client
    networks:
      - app-tier