#name: fc-local
version: "3"

services:

  py-client:
    container_name: py-client
    image: py-client:latest
    restart: unless-stopped
    depends_on: [db-client]
    build:
      context: ./client
      dockerfile: Dockerfile
    entrypoint: python -u /client.py py-server db-client

  py-server:
    container_name: py-server
    image: py-server:latest
    restart: unless-stopped
    depends_on: [db-server]
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
    entrypoint: python -u /server.py db-server 27017

  db-server:
    container_name: db-server
    image: 'mongo:4.4.6'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=serv
      - MONGO_INITDB_ROOT_PASSWORD=serv123
      - MONGO_INITDB_DATABASE=serv_db
    ports:
      - "27017:27017"
    volumes:
      - ./server/db:/data/db

  db-client:
    container_name: db-client
    image: 'mongo:4.4.6'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cl
      - MONGO_INITDB_ROOT_PASSWORD=cl123
      - MONGO_INITDB_DATABASE=cl_db
    ports:
      - "27018:27017"
    volumes:
      - ./client/db:/data/db