name: cloud-node

services:

  py-server:
    container_name: py-server
    image: py-server:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "50000:50000"

  mongodb:
    container_name: mongodb
    image: 'mongo:4.4.6'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cl
      - MONGO_INITDB_ROOT_PASSWORD=cl123
      - MONGO_INITDB_DATABASE=cl_db
    ports:
      - "27017:27017"